########Exponential distribution

# First create set of random numbers - I've named it Rs

m=2^31-1
a=7^5
x=987654321
c=100000

Rs=c()

#num is the number of random numbers to create
num=10
for(i in 1:num){
  x=(a*x+c)%%m
  R=x/m
  Rs[i]=R
}

Rs

# create the set of num-number of random variables based on the elements of Rs
# Say the random variables are exponential distributed with lambda=1/5 customers per minute
# in other words the mean time between arrivals is 5 minutes

get_Exponvar=function(R)return(-(1/lambda)*log(1-R))

lambda=1/5 #arrivals/minutes

MyIATS=sapply(Rs,get_Exponvar)

MyIATS

#Check for yourself - the larger the number random variables the closer the mean will get
# to 1/lambda
mean(MyIATS)

#The same set of interarrival times could also be generated by the qexp function of R

MyIATs_Alt=qexp(Rs,lambda)
MyIATs_Alt


########Uniform distribution

# First create set of random numbers - I've named it Rs again

m=2^31-1
a=7^5
x=654321987
c=100000

Rs=c()

#num is the number of random numbers to create
num=20
for(i in 1:num){
  x=(a*x+c)%%m
  R=x/m
  Rs[i]=R
}

Rs

# create the set of num-number of random variables based on the elements of Rs
# Say the random variables service times which are uniform distributed 
# with a=15 minutes and b=45 minutes 

get_Unifvar=function(R)return(a+(b-a)*R)


a=15
b=45

My_STs=sapply(Rs,get_Unifvar)

My_STs

#Discrete distributions

m=2^31-1
a=7^5
x=1312322333
c=0

Rs=c()

num=10
for(i in 1:num){
  x=(a*x+c)%%m
  R=x/m
  Rs[i]=R
}

Rs

# Buta discrete demands

dem=matrix(c(100,150,200,250,300,350,400,0.05,0.15,0.2,0.25,0.2,0.1,0.05),ncol=2)
dem

lastub=dem[1,2]

ubs=c()
ubs[1]=lastub

numintervals=dim(dem)[1]

for(i in 2:numintervals){
  lastub=lastub+dem[i,2]
  ubs[i]=lastub
}
ubs

lbs=c(0)
for(i in 2:numintervals){
  lbs[i]=ubs[i-1]
}
lbs

bounds=data.frame(lbs,ubs)

bounds

num=100

sdem=c()

x=111222333

for(i in 1:num){
  x=(a*x+c)%%m
  R=x/m
  j=1
  found=FALSE
  while(found==FALSE){
    if(lbs[j] <= R & R <ubs[j]){
      found=TRUE
      sdem[i]=dem[j,1]
    }
    j=j+1
  }
  cat("\n",R,"  ",sdem[i])
}
sdem

#hist(sdem)

table(sdem)

t(dem)


plot(table(sdem))





#Bernoulli trials simulated

# A Bernoulli random variable is the number 
# of successes X in one Bernoulli trial, 
# X = 0 or 1 only,
# where the probability of a success is p.



p=0.15

S=c()
for(i in 1:num)if(Rs[i]<=p){S[i]=1}else{S[i]=0}
S


S=c()
x=1312322332
for(i in 1:num){
  x=(a*x+c)%%m
  R=x/m
  if(R<=p){S[i]=1}else{S[i]=0}
}
S


# Binomial trials simulated

# A Binomial random variable is the number of successes Y
# of n-number of independent identical Bernoulli trials with 
# probability of success p delivering X_j, j in {1..n},
# Y=X_1+X_2+...+X_n.


num=10

p=0.2
n=5

binoms=c()
x=1312322333
for(j in 1:num){
  S=c()
  for(i in 1:n){
    x=(a*x+c)%%m
    R=x/m
    if(R<=p){S[i]=1}else{S[i]=0}
    binoms[j]=sum(S)
 
  }
  cat("\n",S,"  ",sum[S])
}
binoms

mean(binoms)

# Number of arrivals per day


lambda=20

AT=0
A=0
while(AT<=1){
  A=A+1
  x=(a*x+c)%%m
  R=x/m
  AT=AT+(-1*(1/lambda)*log(1-R))
  cat("\n",AT," ",A)
  }
A-1


num=15

lambda=20

ARRs=c()

for(i in 1:num){

AT=0
A=0
while(AT<=1){
  A=A+1
  x=(a*x+c)%%m
  R=x/m
  AT=AT+(-1*(1/lambda)*log(1-R))
  cat("\n",AT," ",A)
}

ARRs[i]=A-1
}
ARRs

hist(ARRs)

qpois

hist(rpois(num,20))

qpois(0.5,lambda)

num=20

m=2^31-1
a=7^5
c=123456
x=987654321

# Simulating number of arrivals per time unit with 
# the inverse Poisson function of R.

ARRs=c()
for(i in 1: num){
  x=(a*x+c)%%m
  R=x/m  
  ARRs[i]=qpois(R,lambda)
}
ARRs